apiVersion: v1
kind: Service
metadata:
  name: enterprise-gateway
  namespace: enterprise-gateway
  labels:
    app: enterprise-gateway

spec:
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 32544
  selector:
    gateway-selector: enterprise-gateway
  type: NodePort
  sessionAffinity: ClientIP
  externalTrafficPolicy: Cluster
