apiVersion: v1
kind: ServiceAccount
metadata:
  name: enterprise-gateway-sa
  namespace: { { .Values.namespace | quote } }
  labels:
    app: enterprise-gateway
    component: enterprise-gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: { { .Values.namespace | quote } }
  name: enterprise-gateway-controller
  labels:
    app: enterprise-gateway
    component: enterprise-gateway
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "namespaces", "services", "configmaps", "secrets", "persistentvolumnes", "persistentvolumeclaims" ]
    verbs: [ "get", "watch", "list", "create", "delete" ]
  - apiGroups: [ "rbac.authorization.k8s.io","" ]
    resources: [ "rolebindings" ]
    verbs: [ "get", "list", "create", "delete","watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: { { .Values.namespace | quote } }
  name: enterprise-gateway-controller
  labels:
    app: enterprise-gateway
    component: enterprise-gateway
subjects:
  - kind: ServiceAccount
    name: enterprise-gateway-sa
    namespace: enterprise-gateway
roleRef:
  kind: Role
  name: enterprise-gateway-controller
  apiGroup: rbac.authorization.k8s.io
