apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configs
  namespace: { { .Values.namespace | quote } }
data:
  EG_REMOVE_CONTAINER: 'False'
  EG_NAMESPACE: { { .Values.namespace | quote } }
  EG_KERNEL_CLUSTER_ROLE: "kernel-controller"
  EG_SHARED_NAMESPACE: 'True'
  KG_ALLOW_ORIGIN: '*'
  KG_ALLOW_METHODS: '*'
  KG_ALLOW_HEADERS: '*'
  KG_ALLOW_CREDENTIALS: 'True'
  KG_LIST_KERNELS: 'True'
  EG_TUNNELING_ENABLED: "False"
  EG_CULL_IDLE_TIMEOUT: "600"
  EG_LOG_LEVEL: "DEBUG"
  EG_KERNEL_LAUNCH_TIMEOUT: "60"
  EG_AUTH_TOKEN: "xyz"
  KERNEL_SPARK_CONTEXT_INIT_MODE: eager
  EG_KERNEL_WHITELIST: "['r_kubernetes','python_kubernetes','python_tf_kubernetes','scala_kubernetes','spark_r_kubernetes','spark_python_kubernetes','spark_scala_kubernetes']"
  SPARK_HOME: /usr/local/spark
  PYSPARK_PYTHON: /usr/bin/python3
  PYSPARK_DRIVER_PYTHON: /usr/bin/python3
  SPARK_OPTS: --conf spark.executor.memory=4g

